name: Publish Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Confirm release version
        run: echo "Bundling ${{ env.RELEASE_VERSION }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Bundle
        run: yarn export-js-output
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: './output'
          filename: '${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}.zip'
      - uses: ncipollo/release-action@v1
        with:
          artifacts: './output/${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
